<?php
/**
 * `InstalledVersions` classmap entry is not prefixed when Strauss itself is prefixed (i.e. `strauss.phar`).
 *
 * Composer's `AutoloadGenerator::dump()` hardcodes the string `'Composer\InstalledVersions'` when adding the class
 * to the classmap. When Strauss is distributed with its own dependencies prefixed, that string has been rewritten to
 * `'BrianHenryIE\Strauss\Composer\InstalledVersions'`, so the generated `vendor-prefixed/composer/autoload_static.php`
 * and `autoload_classmap.php` refer to a class that does not exist, while the copied
 * `vendor-prefixed/composer/InstalledVersions.php` is correctly prefixed to the project's namespace.
 *
 * @see \Composer\Autoload\AutoloadGenerator::dump()
 * @see \BrianHenryIE\Strauss\Pipeline\Autoload\DumpAutoload::createInstalledVersionsFiles()
 * @see \BrianHenryIE\Strauss\Pipeline\Prefixer::prefixComposerAutoloadFiles()
 *
 * @see https://github.com/BrianHenryIE/strauss/issues/301
 */

namespace BrianHenryIE\Strauss\Tests\Issues;

use BrianHenryIE\Strauss\Config\PrefixerConfigInterface;
use BrianHenryIE\Strauss\Files\DiscoveredFiles;
use BrianHenryIE\Strauss\IntegrationTestCase;
use BrianHenryIE\Strauss\Pipeline\Prefixer;
use Mockery;

/**
 * @package BrianHenryIE\Strauss\Tests\Issues
 * @coversNothing
 */
class StraussIssue301Test extends IntegrationTestCase
{

    /**
     * Simulate the output of `DumpAutoload::generatedPrefixedAutoloader()` when run from `strauss.phar`:
     *
     * - `InstalledVersions.php` is copied from the project's `vendor/composer` so declares `namespace Composer;`.
     * - `autoload_classmap.php` and `autoload_static.php` are written by Strauss's bundled (prefixed) copy of
     *   Composer, whose hardcoded `'Composer\InstalledVersions'` classmap entry was rewritten to
     *   `'BrianHenryIE\Strauss\Composer\InstalledVersions'` when Strauss prefixed itself.
     */
    public function test_installed_versions_classmap_entry_is_prefixed_when_strauss_is_self_prefixed(): void
    {
        $targetDirectory = $this->testsWorkingDir . '/vendor-prefixed';

        $installedVersionsPhpString = <<<'EOD'
<?php

namespace Composer;

use Composer\Autoload\ClassLoader;

class InstalledVersions
{
}
EOD;

        $autoloadClassmapPhpString = <<<'EOD'
<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'BrianHenryIE\\Strauss\\Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
EOD;

        $autoloadStaticPhpString = <<<'EOD'
<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4b0b1b6ad2c2a0e3f6f5f2c07d5a0f1c
{
    public static $classMap = array (
        'BrianHenryIE\\Strauss\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit4b0b1b6ad2c2a0e3f6f5f2c07d5a0f1c::$classMap;
        }, null, ClassLoader::class);
    }
}
EOD;

        $this->getFileSystem()->write($targetDirectory . '/composer/InstalledVersions.php', $installedVersionsPhpString);
        $this->getFileSystem()->write($targetDirectory . '/composer/autoload_classmap.php', $autoloadClassmapPhpString);
        $this->getFileSystem()->write($targetDirectory . '/composer/autoload_static.php', $autoloadStaticPhpString);

        $config = Mockery::mock(PrefixerConfigInterface::class);
        $config->allows('getNamespacePrefix')->andReturn('BrianHenryIE\\WP_Secrets');
        $config->allows('getConstantsPrefix')->andReturn('BHIE_WP_SECRETS_');
        $config->allows('getAbsoluteTargetDirectory')->andReturn($targetDirectory);
        $config->allows('isTargetDirectoryVendor')->andReturnFalse();
        $config->allows('isDryRun')->andReturnFalse();

        $prefixer = new Prefixer(
            $config,
            $this->getFileSystem(),
            $this->getTestLogger()
        );

        $prefixer->prefixComposerAutoloadFiles($targetDirectory, new DiscoveredFiles());

        // The class declaration is correctly prefixed (this already works).
        $installedVersionsPhpString = $this->getFileSystem()->read($targetDirectory . '/composer/InstalledVersions.php');
        $this->assertStringNotContainsString('namespace Composer;', $installedVersionsPhpString);
        $this->assertStringContainsString('namespace BrianHenryIE\WP_Secrets\Composer;', $installedVersionsPhpString);

        // The classmap entries must refer to the same class.
        $autoloadClassmapPhpString = $this->getFileSystem()->read($targetDirectory . '/composer/autoload_classmap.php');
        $this->assertStringNotContainsString(
            '\'BrianHenryIE\\\\Strauss\\\\Composer\\\\InstalledVersions\'',
            $autoloadClassmapPhpString,
            'InstalledVersions still has Strauss\'s own prefix in autoload_classmap.php.'
        );
        $this->assertStringContainsString(
            '\'BrianHenryIE\\\\WP_Secrets\\\\Composer\\\\InstalledVersions\'',
            $autoloadClassmapPhpString,
            'InstalledVersions not prefixed in autoload_classmap.php.'
        );

        $autoloadStaticPhpString = $this->getFileSystem()->read($targetDirectory . '/composer/autoload_static.php');
        $this->assertStringNotContainsString(
            '\'BrianHenryIE\\\\Strauss\\\\Composer\\\\InstalledVersions\'',
            $autoloadStaticPhpString,
            'InstalledVersions still has Strauss\'s own prefix in autoload_static.php.'
        );
        $this->assertStringContainsString(
            '\'BrianHenryIE\\\\WP_Secrets\\\\Composer\\\\InstalledVersions\'',
            $autoloadStaticPhpString,
            'InstalledVersions not prefixed in autoload_static.php.'
        );
    }
}
